// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrO445woh4iUAD1moBjNT2dtIJe52tb34',
    appId: '1:1063728497269:web:3699a76683439661d62e3c',
    messagingSenderId: '1063728497269',
    projectId: 'nabd-app-98ea7',
    authDomain: 'nabd-app-98ea7.firebaseapp.com',
    storageBucket: 'nabd-app-98ea7.firebasestorage.app',
    measurementId: 'G-04TNDKHNHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi8KIaS9GTMbeY7NFeHiLgxhQkzP19cvc',
    appId: '1:1063728497269:android:526f557b6f737bead62e3c',
    messagingSenderId: '1063728497269',
    projectId: 'nabd-app-98ea7',
    storageBucket: 'nabd-app-98ea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBrFh08U3zjBaotcbblOMHlQw0im7CEw0',
    appId: '1:1063728497269:ios:d51efb63d0e4b763d62e3c',
    messagingSenderId: '1063728497269',
    projectId: 'nabd-app-98ea7',
    storageBucket: 'nabd-app-98ea7.firebasestorage.app',
    iosBundleId: 'com.nwit.nabdClientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBrFh08U3zjBaotcbblOMHlQw0im7CEw0',
    appId: '1:1063728497269:ios:d51efb63d0e4b763d62e3c',
    messagingSenderId: '1063728497269',
    projectId: 'nabd-app-98ea7',
    storageBucket: 'nabd-app-98ea7.firebasestorage.app',
    iosBundleId: 'com.nwit.nabdClientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrO445woh4iUAD1moBjNT2dtIJe52tb34',
    appId: '1:1063728497269:web:b869450758921290d62e3c',
    messagingSenderId: '1063728497269',
    projectId: 'nabd-app-98ea7',
    authDomain: 'nabd-app-98ea7.firebaseapp.com',
    storageBucket: 'nabd-app-98ea7.firebasestorage.app',
    measurementId: 'G-JSEVNWE9F5',
  );
}
